export * from "@/pages/staff/dashboard.jsx";
export * from "@/pages/admin/admin-add-hall-ticket";
export * from "@/pages/admin/admin-add-attendance";
export * from "@/pages/staff/staff-marks-entry.jsx";
export * from "@/pages/staff/staff-manual-marks-entry.jsx";
export * from "@/pages/admin/admin-add-report-card";
export * from "@/pages/admin/admin-reports"
export * from "@/pages/admin/admin-profile.jsx";
export * from "@/pages/admin/superAdmin-view-student-fees"